version: '3.8'

services:
  sftp-server:
    image: atmoz/sftp
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./pysros:/home/admin/pysros
      # - ./sftp-keys:/home/giancarlo3g/.ssh/ssh_host_keys
    environment:
      - SFTP_USERS=admin:admin:1001:1001:upload
    restart: unless-stopped
    command: admin:admin:1001:1001:upload

  tftp-server:
    image: pghalliday/tftp
    container_name: tftp-server
    ports:
      - "69:69/udp"
    volumes:
      - ./pysros:/var/tftpboot
    restart: unless-stopped
    environment:
      - TFTP_OPTIONS=--secure --create