services:
  # SFTP server
  sftp-server:
    image: atmoz/sftp
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./pysros:/home/admin/pysros
    environment:
      - SFTP_USERS=admin:admin:1001:1001:upload
    restart: unless-stopped
    command: admin:admin:1001:1001:upload
  # TFTP server from local Dockerfile
  tftp-server:
    build:
      context: .
      dockerfile: Dockerfile.tftp
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: tftp-server
    ports:
      - "69:69/udp"
    volumes:
      - ./pysros:/var/tftpboot
    restart: unless-stopped